# Generated by Django 5.1.2 on 2024-12-01 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
                ('dificultad', models.CharField(choices=[('Fácil', 'Facil'), ('Media', 'Media'), ('Díficil', 'Dificil')], default='Media', max_length=8)),
                ('tiempo_preparacion', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen_url', models.ImageField(upload_to='images/')),
                ('es_premium', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado')], default='Pendiente', max_length=10)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('receta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.receta')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('Paypal', 'Paypal'), ('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('American express', 'American Express')], default='Visa', max_length=20)),
                ('compra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.compra')),
            ],
        ),
    ]
